"""empty message

Revision ID: 1a2f8e7bffe7
Revises: 5f5bf4d7de44
Create Date: 2023-07-28 19:08:09.475733

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1a2f8e7bffe7'
down_revision = '5f5bf4d7de44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
