"""empty message

Revision ID: 1ef38c8c0e1b
Revises: b8bff6577201
Create Date: 2023-07-28 18:49:10.536100

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1ef38c8c0e1b'
down_revision = 'b8bff6577201'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
