"""empty message

Revision ID: 1fb36f9378f7
Revises: 1ef38c8c0e1b
Create Date: 2023-07-28 19:00:40.320661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb36f9378f7'
down_revision = '1ef38c8c0e1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
