"""y

Revision ID: 28ec5a6dfcdb
Revises: a95eee1aaac8
Create Date: 2023-07-29 12:57:47.917137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ec5a6dfcdb'
down_revision = 'a95eee1aaac8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
