"""empty message

Revision ID: 35f8c3fde5c4
Revises: fd5c880199f6
Create Date: 2023-08-17 19:18:22.303893

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '35f8c3fde5c4'
down_revision = 'fd5c880199f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
