"""empty message

Revision ID: 47075a9a9f5c
Revises: 602a48f61477
Create Date: 2023-07-29 15:33:21.170387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47075a9a9f5c'
down_revision = '602a48f61477'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
