"""empty message

Revision ID: 4d1d8d602e68
Revises: 28ec5a6dfcdb
Create Date: 2023-07-29 13:00:19.622987

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4d1d8d602e68'
down_revision = '28ec5a6dfcdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
