"""empty message

Revision ID: 53cdf532e782
Revises: 930f564f85c0
Create Date: 2023-07-28 19:17:31.452645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53cdf532e782'
down_revision = '930f564f85c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
