"""empty message

Revision ID: 5aaa79a36641
Revises: 5798c2126723
Create Date: 2023-07-28 18:36:36.927028

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5aaa79a36641'
down_revision = '5798c2126723'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
