"""empty message

Revision ID: 5f5bf4d7de44
Revises: 1fb36f9378f7
Create Date: 2023-07-28 19:02:31.948695

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5f5bf4d7de44'
down_revision = '1fb36f9378f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
