"""empty message

Revision ID: 602a48f61477
Revises: d296e56b45fa
Create Date: 2023-07-29 15:28:42.823746

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '602a48f61477'
down_revision = 'd296e56b45fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
