"""empty message

Revision ID: 930f564f85c0
Revises: d159764fc2a0
Create Date: 2023-07-28 19:16:19.987955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930f564f85c0'
down_revision = 'd159764fc2a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
