"""empty message

Revision ID: 9f9e0bd1e7e3
Revises: 53cdf532e782
Create Date: 2023-07-28 19:18:16.824064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9e0bd1e7e3'
down_revision = '53cdf532e782'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
