"""empty message

Revision ID: a95eee1aaac8
Revises: f5270ec65467
Create Date: 2023-07-28 19:20:54.831762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95eee1aaac8'
down_revision = 'f5270ec65467'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
