"""empty message

Revision ID: aca4d2c7ce64
Revises: 9f9e0bd1e7e3
Create Date: 2023-07-28 19:19:06.396816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca4d2c7ce64'
down_revision = '9f9e0bd1e7e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
