"""empty message

Revision ID: b8bff6577201
Revises: 5aaa79a36641
Create Date: 2023-07-28 18:43:47.658903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bff6577201'
down_revision = '5aaa79a36641'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
