"""empty message

Revision ID: cde2c1c9da94
Revises: 4d1d8d602e68
Create Date: 2023-07-29 14:46:24.801111

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cde2c1c9da94'
down_revision = '4d1d8d602e68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
