"""empty message

Revision ID: d159764fc2a0
Revises: 1a2f8e7bffe7
Create Date: 2023-07-28 19:09:20.495060

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd159764fc2a0'
down_revision = '1a2f8e7bffe7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
