"""empty message

Revision ID: d296e56b45fa
Revises: cde2c1c9da94
Create Date: 2023-07-29 15:21:33.872565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd296e56b45fa'
down_revision = 'cde2c1c9da94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
