"""empty message

Revision ID: ea7603692e72
Revises: 47075a9a9f5c
Create Date: 2023-07-29 15:35:20.007011

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ea7603692e72'
down_revision = '47075a9a9f5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
