"""empty message

Revision ID: f5270ec65467
Revises: aca4d2c7ce64
Create Date: 2023-07-28 19:19:55.427388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5270ec65467'
down_revision = 'aca4d2c7ce64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
